// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Gacha","status":true,"description":"Get the item at random","parameters":{"Help Message Text":"1回Required Amount\\Gでガチャを引きます","Button Text":"ガチャを引く","Get Message Text":"GET Item Name","Show Item Description":"0","Effect":"119","Rank1 Effect":"-1","Rank2 Effect":"-1","Rank3 Effect":"-1","Rank4 Effect":"-1","Rank5 Effect":"-1","ME":"Organ","Required Amount":"100"}},
{"name":"GachaBook","status":true,"description":"Displays detailed statuses of \"gacha\" items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type","Rank Text":"Rank","Simple Display":"0"}},
{"name":"FTKR_TitleScene","status":true,"description":"v1.0.1 修改標題畫面的插件","parameters":{"コンティニューコマンド":"1","オプションコマンド":"1","クレジットコマンド":"","コマンドウィンドウ設定":"{\"fontsize\":\"28\",\"padding\":\"18\",\"lineHeight\":\"36\",\"opacity\":\"192\",\"hideFrame\":\"1\"}"}}
];
